---
- name: Install required packages
  ansible.builtin.shell: yum install -y nginx python3-pip git unzip
  args:
    creates: /usr/sbin/nginx
  become: yes

- name: Start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  notify: reload nginx

- name: Harden SSH - disable root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: restart sshd
