---
- name: Configure EC2 Instance
  hosts: all
  become: yes

  tasks:
    - name: Install nginx from Amazon Linux Extras
      shell: amazon-linux-extras install nginx1 -y

    - name: Install other required packages
      yum:
        name:
          - python3-pip
          - git
          - unzip
        state: present

    - name: Enable and start nginx
      systemd:
        name: nginx
        enabled: yes
        state: started

